# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: poetry-install
description: Install Python and Poetry

inputs:
  python-version:
    description: "Python version"
    required: false
  poetry-version:
    description: "Poetry version"
    required: false

runs:
  using: "composite"
  steps:
    - id: set-env
      name: Set environment
      env:
        INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
        INPUT_POETRY_VERSION: ${{ inputs.poetry-version }}
      run: |
        set -x

        if [[ -n $PYTHON_VERSION ]]; then
          python_version=$PYTHON_VERSION
        elif [[ -n $INPUT_PYTHON_VERSION ]]; then
          python_version=$INPUT_PYTHON_VERSION
        else
          python_version=3.13.12
        fi

        if [[ -n $POETRY_VERSION ]]; then
          poetry_version=$POETRY_VERSION
        elif [[ -n $INPUT_POETRY_VERSION ]]; then
          poetry_version=$INPUT_POETRY_VERSION
        else
          poetry_version=2.3.2
        fi

        echo python-version=$python_version >> "$GITHUB_OUTPUT"
        echo poetry-version=$poetry_version >> "$GITHUB_OUTPUT"
      shell: bash

    - uses: actions/setup-python@v6
      with:
        python-version: ${{ steps.set-env.outputs.python-version }}
        # NOTE: remove the poetry cache because it's not so fast.
        # Note that to make it work, you need to run actions/checkout@v6
        # with: ref: ${{ case(github.event_name == 'pull_request', github.head_ref, '') }}
        # Then follow https://github.com/actions/setup-python/blob/v6/docs/advanced-usage.md#caching-packages
        # cache: poetry

    - name: Install poetry
      run: |
        set -x
        pip install --only-binary=:all: poetry==${{ steps.set-env.outputs.poetry-version }}
        pip install --only-binary=:all: poetry-dynamic-versioning==1.10.0
      shell: bash
