# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check code quality on all repositories

# on:
#   workflow_dispatch:

on:
  push # TEMP !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

jobs:
  # For each repository, get the most relevant branch name: current branch name, or develop, or main, or master.
  all-repos:
    name: Get repo info
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.setup.outputs.repo_names }}
      info: ${{ steps.setup.outputs.repo_info }}
    steps:
      - id: setup
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x

          # Build json arrays by hand
          repo_names="["
          repo_info="{"

          # For each repository name from this organization
          for repo_name in $(gh repo list ${{ github.repository_owner }} --json name | jq -r '.[].name'); do

            # Ignore these repos
            ignore=" upptime pygeofilter .github rs-annexes RS-PYTHON.github.io local-pypi rs-statuspage rs-issues "
            [[ $ignore =~ " $repo_name " ]] && continue

            # TEMP, to test only specific repos
            # [[ ! " opentelemetry-instrumentation-eopf rs-testmeans " =~ " $repo_name " ]] && continue

            # Test if the current branch name exists for this repo.
            # Then test develop, main and master.
            for test_branch_name in ${{ github.ref_name }} develop main and master; do
              if gh api repos/${{ github.repository_owner }}/${repo_name}/branches/${test_branch_name} --silent; then
                ref_name=$test_branch_name
                if [[ $test_branch_name == ${{ github.ref_name }} ]]; then
                  ref=${{ github.ref }}
                else
                  ref=$test_branch_name
                fi
                break
              fi
            done

            # Update the json array with repo_name
            repo_names="${repo_names}\"${repo_name}\","

            # Update the json dict whith <repo_name>:{ref:<ref>,ref_name:<ref_name>},
            repo_info="${repo_info}\"${repo_name}\":{\"ref\":\"${ref}\",\"ref_name\":\"${ref_name}\"},"
          done
          echo "repo_names=${repo_names}]" >> $GITHUB_OUTPUT
          echo "repo_info=${repo_info}}" >> $GITHUB_OUTPUT

  # Check quality of all repositories
  call-all-repos:
    name: Call all repos
    needs: all-repos
    uses: ./.github/workflows/reusable-check-quality.yml
    with:
        caller-repository: ${{ github.repository_owner }}/${{ matrix.repo }}
        caller-ref: ${{ fromJson(needs.all-repos.outputs.info)[matrix.repo]['ref'] }}
        caller-ref_name: ${{ fromJson(needs.all-repos.outputs.info)[matrix.repo]['ref'] }}
        python-version: ${{ matrix.python-version }}
        poetry-version: ${{ matrix.poetry-version }}
        run-trivy: ${{ matrix.run-trivy }}
        ignore-bandit-errors: ${{ matrix.ignore-bandit-errors }}
        ignore-flake8-errors: ${{ matrix.ignore-flake8-errors }}
        ignore-mypy-errors: ${{ matrix.ignore-mypy-errors }}
        ignore-pylint-errors: ${{ matrix.ignore-pylint-errors }}
        ignore-safety-errors: ${{ matrix.ignore-safety-errors }}
        cov-dirs: ${{ matrix.cov-dirs }}
        sonar-cov-exclusions: ${{ matrix.sonar-cov-exclusions }}
        sonar-exclusions: ${{ matrix.sonar-exclusions }}
    secrets:
      SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: write # for apache/skywalking-eyes/header
      pull-requests: write # for apache/skywalking-eyes/header and phwt/sonarqube-quality-gate-action
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.all-repos.outputs.names) }}
        include:

          # Default option values
          - python-version: 3.13.12
          - poetry-version: 2.3.2
          - run-trivy: true
          - ignore-bandit-errors: false
          - ignore-flake8-errors: false
          - ignore-mypy-errors: false
          - ignore-pylint-errors: false
          - ignore-safety-errors: false
          - cov-dirs: .
          - sonar-cov-exclusions: tests,tests/**,**/tests/**
          - sonar-exclusions: tests,tests/**,**/tests/**

          # Options specific to each git repo
          - repo: opentelemetry-instrumentation-eopf
            python-version: 3.12

          - repo: rs-client-libraries
            cov-dirs: "rs_client,rs_common,rs_workflows"
            sonar-cov-exclusions: tests,tests/**,**/tests/**,rs_workflows/on_demand/**,rs_workflows/operation/**,rs_workflows/utils/**

          - repo: rs-testmeans
            ignore-bandit-errors: true
            ignore-flake8-errors: true
            ignore-mypy-errors: true
            ignore-pylint-errors: true
