# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Check code quality

on:
  push:
#   pull_request:
  workflow_dispatch:

jobs:
  # call-reusable-workflow:
  #   name: _
  #   uses: RS-PYTHON/actions/.github/workflows/reusable-check-quality.yml@feat-rspy995/run-sonar-from-project-root
  #   with:
  #       # caller-repository: ${{ github.repository }}
  #       # caller-ref: ${{ github.ref }}

  #       caller-repository: RS-PYTHON/rs-server
  #       caller-ref: refs/heads/feat-rspy995/run-sonar-from-project-root

  #   secrets:
  #     SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #   permissions:
  #     contents: write # for apache/skywalking-eyes/header
  #     pull-requests: write # for apache/skywalking-eyes/header and phwt/sonarqube-quality-gate-action

  # rs-testmeans:
  #   name: rs-testmeans
  #   uses: RS-PYTHON/actions/.github/workflows/reusable-check-quality.yml@feat-rspy995/run-sonar-from-project-root
  #   with:
  #       caller-repository: RS-PYTHON/rs-testmeans
  #       caller-ref: refs/heads/feat-rspy995/run-sonar-from-project-root
  #       ignore-bandit-errors: true
  #       ignore-flake8-errors: true
  #       ignore-mypy-errors: true
  #       ignore-pylint-errors: true
  #   secrets:
  #     SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #   permissions:
  #     contents: write # for apache/skywalking-eyes/header
  #     pull-requests: write # for apache/skywalking-eyes/header and phwt/sonarqube-quality-gate-action

  # rs-client-libraries:
  #   name: rs-client-libraries
  #   uses: RS-PYTHON/actions/.github/workflows/reusable-check-quality.yml@feat-rspy995/run-sonar-from-project-root
  #   with:
  #       caller-repository: RS-PYTHON/rs-client-libraries
  #       caller-ref: refs/heads/feat-rspy995/run-sonar-from-project-root
  #       test-covered-dirs: "rs_client rs_common rs_workflows"
  #   secrets:
  #     SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
  #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  #   permissions:
  #     contents: write # for apache/skywalking-eyes/header
  #     pull-requests: write # for apache/skywalking-eyes/header and phwt/sonarqube-quality-gate-action

  opentelemetry-instrumentation-eopf:
    name: opentelemetry-instrumentation-eopf
    uses: RS-PYTHON/actions/.github/workflows/reusable-check-quality.yml@feat-rspy995/run-sonar-from-project-root
    with:
        caller-repository: RS-PYTHON/opentelemetry-instrumentation-eopf
        caller-ref: main
    secrets:
      SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: write # for apache/skywalking-eyes/header
      pull-requests: write # for apache/skywalking-eyes/header and phwt/sonarqube-quality-gate-action

  cadip-stac-extension:
    name: cadip-stac-extension
    uses: RS-PYTHON/actions/.github/workflows/reusable-check-quality.yml@feat-rspy995/run-sonar-from-project-root
    with:
        caller-repository: RS-PYTHON/cadip-stac-extension
        caller-ref: main
    secrets:
      SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    permissions:
      contents: write # for apache/skywalking-eyes/header
      pull-requests: write # for apache/skywalking-eyes/header and phwt/sonarqube-quality-gate-action
