# Copyright 2023-2026 Airbus, CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Clean old Docker images

# Run workflow only for ...
on:
  workflow_dispatch: # manual trigger
  schedule: # works only on the default branch !
    - cron: "*/5 * * * *" # every 5 minutes
    - cron: "0 0 * * *" # every day at 00:00
  # push: # on every push, for testing only

env:
  RUN_PARALLEL: false # it may be better to run in sequential if we have "rate limit" http errors
  DRY_RUN: false # if true: don't delete images for real, only print log
  CACHE_KEY: cache-clean-old-docker # name of the github ci/cd cache where we save the manifest lists
  CACHE_DIR: ./js/cache # where this cache is saved on local
  PRINT_CACHE: false # print cache contents, before and after processing

jobs:
  get-images:
    name: Get all docker images
    runs-on: ubuntu-latest
    outputs:
      imagesByRepo: ${{ steps.get-images.outputs.imagesByRepo }}
      jobs: ${{ steps.get-images.outputs.jobs }}
    steps:
      - uses: actions/checkout@v7
      - id: get-images
        name: Get all docker images
        uses: actions/github-script@v9 # run javascript
        env:
          GITHUB_PAT: ${{ secrets.CLEAN_DOCKER_IMAGES }} # github pat with delete:packages,read:packages
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Init octokit, see https://octokit.github.io/rest.js
            const appOctokit = getOctokit(process.env.GITHUB_PAT)

            // Import custom module and get all docker images, sorted by repository
            const { default: mod } = await import('${{ github.workspace }}/js/clean-old-docker.js')
            const imagesByRepo = await mod.getImages(appOctokit)

            // Convert map {repo1: [img1, img2], repo2: [img3, img4]} into
            // [{"repo": repo1, "images": [img1, img2]}, {"repo": repo2, "images": [img3, img4]}]
            // that will be used in the below matrix
            const jobs = []
            imagesByRepo.forEach((value, key) => {jobs.push({"repo": key, "images": value})})

            // Write results to github outputs
            const fs = require("fs")
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `imagesByRepo=${mod.jsonStringifyMap(imagesByRepo, 0)}\n`)
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `jobs=${JSON.stringify(jobs)}\n`)

  clean-repos-parallel:
    name: Clean from ${{ matrix.job.repo }}
    runs-on: ubuntu-latest
    needs: get-images
    permissions: # to remove old cache
      actions: write
      contents: read
    strategy:
      matrix:
        job: ${{ fromJSON(needs.get-images.outputs.jobs) }}
      fail-fast: false
    steps:
      - if: ${{ env.RUN_PARALLEL == 'true' }}
        uses: actions/checkout@v7

      - if: ${{ env.RUN_PARALLEL == 'true' }}
        name: Restore cache
        uses: actions/cache/restore@v6
        with:
          key: ${{ env.CACHE_KEY }}-${{ matrix.job.repo }}
          path: ${{ env.CACHE_DIR }}/**

      - if: ${{ env.RUN_PARALLEL == 'true' }}
        name: Clean ${{ matrix.job.repo }} images
        env:
          GITHUB_PAT: ${{ secrets.CLEAN_DOCKER_IMAGES }} # github pat with delete:packages,read:packages
        uses: actions/github-script@v9 # run javascript
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const cacheDir = "${{ env.CACHE_DIR }}"

            // Init octokit, see https://octokit.github.io/rest.js
            const appOctokit = getOctokit(process.env.GITHUB_PAT)

            // Import custom module
            const { default: mod } = await import('${{ github.workspace }}/js/clean-old-docker.js')

            // Clean docker images of this git repo
            repo = "${{ matrix.job.repo }}"
            images = ${{ toJSON(matrix.job.images) }}

            // Read cache of manifest lists
            const cacheAllManifests = new Map()
            mod.readCacheManifests(images, cacheAllManifests, cacheDir)

            // Run cleaning
            try {
                console.log(`\n## Clean ${repo} images: ${images} ##\n`)
                await mod.cleanRepo(appOctokit, cacheAllManifests, repo, images, ${{ env.DRY_RUN }})
            }
            // Save the cache, even in case of error
            finally {
                mod.writeCacheManifests(cacheAllManifests, cacheDir)
            }

      - if: ${{ always() && (env.RUN_PARALLEL == 'true') }}
        name: Remove old cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh cache delete ${{ env.CACHE_KEY }}-${{ matrix.job.repo }}
      - if: ${{ always() && (env.RUN_PARALLEL == 'true') }}
        name: Save new cache
        uses: actions/cache/save@v6
        with:
          key: ${{ env.CACHE_KEY }}-${{ matrix.job.repo }}
          path: ${{ env.CACHE_DIR }}/**

  clean-repos-sequential:
    name: Clean all (sequential)
    runs-on: ubuntu-latest
    needs: get-images
    permissions: # to remove old cache
      actions: write
      contents: read
    steps:
      - if: ${{ env.RUN_PARALLEL != 'true' }}
        uses: actions/checkout@v7

      - if: ${{ env.RUN_PARALLEL != 'true' }}
        name: Restore cache
        uses: actions/cache/restore@v6
        with:
          key: ${{ env.CACHE_KEY }}-sequential
          path: ${{ env.CACHE_DIR }}/**

      - if: ${{ env.RUN_PARALLEL != 'true' }}
        name: Clean all
        env:
          GITHUB_PAT: ${{ secrets.CLEAN_DOCKER_IMAGES }} # github pat with delete:packages,read:packages
        uses: actions/github-script@v9 # run javascript
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            readFileSync = require("node:fs").readFileSync
            writeFileSync = require("node:fs").writeFileSync
            join = require("node:path").join
            const cacheDir = "${{ env.CACHE_DIR }}"

            // Init octokit, see https://octokit.github.io/rest.js
            const appOctokit = getOctokit(process.env.GITHUB_PAT)

            // Import custom module
            const { default: mod } = await import('${{ github.workspace }}/js/clean-old-docker.js')

            // Get all docker images, sorted by repository
            let imagesByRepo = ${{ needs.get-images.outputs.imagesByRepo }}
            imagesByRepo = new Map(Object.entries(imagesByRepo))
            console.log(`\nimagesByRepo:\n${mod.jsonStringifyMap(imagesByRepo)}\n`)

            // Read cache of manifest lists
            const cacheAllManifests = new Map()
            imagesByRepo.forEach((images, repo) => mod.readCacheManifests(images, cacheAllManifests, cacheDir))

            // Read from cache the last repo/image that was run and failed on a previous attempt
            var lastRepoRun = ""
            var lastImageRun = ""
            try {
                const cacheFile = join(cacheDir, mod.cacheLastRun)
                const str = readFileSync(cacheFile, "utf8")
                const cached = JSON.parse(str)
                lastRepoRun = cached[0]
                lastImageRun = cached[1]
            }
            catch {}

            // The first repo/image to process is the last that failed
            var firstRepoImage = 0

            // Convert map {repo: [image]} to array [[repo, image]]
            var i = 0
            const repoAndImages = []
            imagesByRepo.forEach((images, repo) => {
                images.forEach(image => {
                    repoAndImages.push([repo, image])

                    // Check if this is the last that failed
                    if ((repo == lastRepoRun) && (image == lastImageRun)) {
                        firstRepoImage = i
                    }
                    ++i
                })
            })

            // Run cleaning on each repo/image
            try {
                for (i = 0; i < repoAndImages.length; ++i)
                {
                    const value = repoAndImages[(i + firstRepoImage) % repoAndImages.length]
                    lastRepoRun = value[0]
                    lastImageRun = value[1]
                    const repo = lastRepoRun
                    const images = [lastImageRun]
                    console.log(`\n## Clean ${repo} images: ${images} ##\n`)
                    await mod.cleanRepo(appOctokit, cacheAllManifests, repo, images, ${{ env.DRY_RUN }})
                }

                // If no repo failed, reset these variables
                lastRepoRun = ""
                lastImageRun = ""
            }

            // Save the cache, even in case of error
            finally
            {
                // Write cache of manifest lists
                mod.writeCacheManifests(cacheAllManifests, cacheDir)

                // Write cache of the last repo/image that was run and failed
                const cacheFile = join(cacheDir, mod.cacheLastRun)
                const str = JSON.stringify([lastRepoRun, lastImageRun])
                writeFileSync(cacheFile, str, "utf8")
            }

      - if: ${{ always() && (env.RUN_PARALLEL != 'true') }}
        name: Remove old cache
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh cache delete ${{ env.CACHE_KEY }}-sequential
      - if: ${{ always() && (env.RUN_PARALLEL != 'true') }}
        name: Save new cache
        uses: actions/cache/save@v6
        with:
          key: ${{ env.CACHE_KEY }}-sequential
          path: ${{ env.CACHE_DIR }}/**
